//Organization
export const ADD_ORGANIZATION = 'ADD_ORGANIZATION'
export const ORGANIZATIONS_ERROR='ORGANIZATIONS_ERROR'
export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS'
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION'
export const SET_CURRENT = 'SET_CURRENT'
export const GET_CURRENT_ORGANIZATION = 'GET_CURRENT_ORGANIZATION'
export const CLEAR_CURRENT = 'CLEAR_CURRENT'
export const CLEAR_ORGANIZATIONS = 'CLEAR_ORGANIZATIONS'
export const SET_LOADING = 'SET_LOADING'
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION'
export const SEARCH_ORGANIZATIONS = 'SEARCH_ORGANIZATIONS'
export const SORT_ORGANIZATIONS = 'SORT_ORGANIZATIONS'
export const FILTER_ORGANIZATIONS = 'FILTER_ORGANIZATIONS'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE '
export const USER_ACCESS='USER_ACCESS'
export const ORGANIZATION_CLEAR_FILTER='ORGANIZATION_CLEAR_FILTER'

//RESPONSE
export const RESPONSE="RESPONSE"
export const CLEAR_RESPONSE="CLEAR_RESPONSE"
//USER
export const ADD_USER = 'ADD_USER'
export const USERS_ERROR='USERS_ERROR'
export const GET_USERS = 'GET_USERS'
export const DELETE_USER = 'DELETE_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'
export const CLEAR_USERS = 'CLEAR_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const SEARCH_USERS = 'SEARCH_USERS'
export const SORT_USERS = 'SORT_USERS'
export const FILTER_USERS = 'FILTER_USERS'
export const CLEAR_USER_MESSAGE = 'CLEAR_USER_MESSAGE '
export const USER_CLEAR_FILTER='USER_CLEAR_FILTER'
export const REGSTEP='REGSTEP'
export const GET_ORG_IN_ACTIVE_USERS='GET_ORG_IN_ACTIVE_USERS'
export const GET_ORG_ACTIVE_USERS='GET_ORG_ACTIVE_USERS'

//Authentication
export const GET_LOGIN = 'GET_LOGIN'
export const SET_LOGIN = 'SET_LOGIN'
export const CLEAR_LOGIN='CLEAR_LOGIN'
export const AUTH_ERROR='AUTH_ERROR'
export const SET_ACCESS='SET_ACCESS'
export const FORGOT_JOURNEY='FORGOT_JOURNEY'
export const RESET_EMAIL='RESET_EMAIL'

//Products
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_ACTIVE_PRODUCTS = 'GET_ACTIVE_PRODUCTS'
export const PRODUCT_ERROR='PRODUCT_ERROR'


//Subscriptions
export const GET_ALL_SUBSCRIPTIONS = 'GET_ALL_SUBSCRIPTIONS'
export const ADD_NEW_SUBSCRIPTION='ADD_NEW_SUBSCRIPTION'
export const SUBSCRIPTION_ERROR='SUBSCRIPTION_ERROR'

//Payment
export const GET_ALL_PAYMENT_METHODS = 'GET_ALL_METHODS'
export const ADD_NEW_PAYMENT_METHOD='ADD_NEW_METHOD'
export const PAYMENT_ERROR='PAYMENT_ERROR'
export const UPDATE_PAYMENT_METHOD='UPDATE_PAYMENT_METHOD'
export const DELETE_PAYMENT_METHOD='DELETE_PAYMENT_METHOD'


//Dataset
export const GET_ALL_DATASETS = 'GET_ALL_DATASETS'
export const GET_SPECIFIC_DATASETS = 'GET_SPECIFIC_DATASETS'
export const ADD_NEW_DATASET='ADD_NEW_DATASET'
export const DATASET_ERROR='DATASET_ERROR'
export const UPDATE_DATASET='UPDATE_DATASET'
export const DELETE_DATASET='DELETE_DATASET'
export const GET_ALL_TABLES='GET_ALL_TABLES'
export const GET_TABLE_DATA='GET_TABLE_DATA'
export const TABLE_LOADING='TABLE_LOADING'
export const SET_CURRENT_DATASET='SET_CURRENT_DATASET'


//Dashboard
export const GET_ALL_DASHBOARDS = 'GET_ALL_DASHBOARDS'
export const ADD_NEW_DASHBOARD='ADD_NEW_DASHBOARD'
export const DASHBOARD_ERROR='DASHBOARD_ERROR'
export const UPDATE_DASHBOARD='UPDATE_DASHBOARD'
export const DELETE_DASHBOARD='DELETE_DASHBOARD'
export const DASHBOARD_LOADING='DASHBOARD_LOADING'
export const SET_CURRENT_DASHBOARD='SET_CURRENT_DASHBOARD'

//Component
export const GET_ALL_COMPONENTS = 'GET_ALL_COMPONENTS'
export const ADD_NEW_COMPONENT='ADD_NEW_COMPONENT'
export const COMPONENT_ERROR='COMPONENT_ERROR'
export const UPDATE_COMPONENT='UPDATE_COMPONENT'
export const DELETE_COMPONENT='DELETE_COMPONENT'
export const COMPONENT_LOADING='COMPONENT_LOADING'
export const SET_CURRENT_COMPONENT='SET_CURRENT_COMPONENT'
export const CLEAR_CURRENT_COMPONENT='CLEAR_CURRENT_COMPONENT'